/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import analizadores.Traductor;
import java.awt.Color;

/**
 *
 * @author audyc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTraducir = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTraduccion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSemantico = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnTraducir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LIMPIAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 740));
        setPreferredSize(new java.awt.Dimension(1000, 740));
        setSize(new java.awt.Dimension(1000, 740));
        getContentPane().setLayout(null);

        txtTraducir.setColumns(20);
        txtTraducir.setRows(5);
        jScrollPane1.setViewportView(txtTraducir);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 900, 130);

        txtTraduccion.setEditable(false);
        txtTraduccion.setColumns(20);
        txtTraduccion.setRows(5);
        jScrollPane2.setViewportView(txtTraduccion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 260, 900, 130);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane3.setViewportView(txtError);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 420, 300, 280);

        txtLexico.setColumns(20);
        txtLexico.setRows(5);
        jScrollPane4.setViewportView(txtLexico);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(370, 420, 260, 280);

        txtSemantico.setColumns(20);
        txtSemantico.setRows(5);
        jScrollPane5.setViewportView(txtSemantico);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(650, 420, 290, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoumg.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 10, 130, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TRADUCTOR DE INGLES A ESPAÑOL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 470, 40);

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setText("X");
        jButton1.setMaximumSize(new java.awt.Dimension(30, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(30, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(950, 0, 50, 40);

        btnTraducir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTraducir.setText("TRADUCIR");
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraducir);
        btnTraducir.setBounds(790, 30, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("TRADUCCION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 220, 180, 40);

        LIMPIAR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LIMPIAR.setText("LIMPIAR");
        LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(LIMPIAR);
        LIMPIAR.setBounds(660, 30, 120, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("-- LEXICO --");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 400, 90, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("-- SEMANTICO --");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 400, 130, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("-- SINTACTICO --");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 400, 140, 17);

        jLabel2.setBackground(new java.awt.Color(204, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        Traductor traduc = new Traductor();
        txtTraduccion.setText(traduc.traducir(txtTraducir.getText()));
        txtError.setText(traduc.Error);
        txtLexico.setText(traduc.LisToken);
        txtError.setForeground(Color.red);
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPIARActionPerformed
        txtError.setText("");
        txtLexico.setText("");
        txtTraduccion.setText("");
        txtTraducir.setText("");
        txtSemantico.setText("");
    }//GEN-LAST:event_LIMPIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LIMPIAR;
    private javax.swing.JButton btnTraducir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextArea txtLexico;
    private javax.swing.JTextArea txtSemantico;
    private javax.swing.JTextArea txtTraduccion;
    private javax.swing.JTextArea txtTraducir;
    // End of variables declaration//GEN-END:variables
}
